name: renovatio
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.36
  audio_waveforms: ^1.0.5
  flutter_slider_drawer: ^2.1.1
  ffmpeg_kit_flutter_new: ^3.2.0
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  health: ^13.2.1
  http: ^1.1.0
  dio: ^5.3.2
  uuid: ^4.0.0
  crypto: ^3.0.3
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/audio/
    - assets/audio/background-audio/
    - assets/audio/background-audio/forest.mp3
    - assets/audio/background-audio/forest.mp4
    - assets/audio/background-audio/ocean-waves.mp4
    - assets/audio/background-music/
    - assets/audio/binaural/
    - assets/audio/binaural/generated/
    - assets/audio/binaural/generated/relax/
    - assets/audio/binaural/generated/sleep/
    - assets/audio/narration/
    - assets/json/
    - lib/schemas/