/// Default narration script pre-loaded on the New Session page.
///
/// Written for a generic ~15-minute wellness session. Uses [pause:Xs] markup
/// consumed by the narration engine: [pause:50s] for a regular breath pause
/// and [pause:70s] for a longer, deeper pause.
///
/// Users may edit this freely or replace it entirely by tapping
/// "Generate Script using AI" once they have configured their session goal.
const String kDefaultNarrationScript =
    'Find a comfortable position, either sitting or lying down. '
    'Allow your body to settle naturally into the surface beneath you. '
    '[pause:50s]'
    'Close your eyes gently, or soften your gaze toward the floor. '
    'There is nothing you need to do right now. '
    'This time is yours. '
    '[pause:70s]'
    'Begin by bringing your attention to your breath. '
    'You do not need to change it. '
    'Simply notice the natural rhythm of each inhale and each exhale. '
    '[pause:50s]'
    'With your next inhale, breathe in slowly and deeply through your nose. '
    '[pause:50s]'
    'And exhale gently through your mouth, releasing any tension you may be holding. '
    '[pause:70s]'
    'Again, breathe in. '
    '[pause:50s]'
    'And breathe out. '
    '[pause:70s]'
    'With each breath, you become a little more relaxed, a little more present. '
    '[pause:50s]'
    'Bring your awareness now to the top of your head. '
    'Notice any tightness there, and let it soften. '
    '[pause:50s]'
    'Let that softness travel slowly down through your forehead, your eyes, your jaw. '
    'Let your face relax completely. '
    '[pause:70s]'
    'Allow it to move down through your neck and your shoulders. '
    'Let your shoulders drop away from your ears. '
    '[pause:50s]'
    'Feel the weight of your arms resting heavily at your sides. '
    'Your hands are open and at ease. '
    '[pause:70s]'
    'The relaxation continues down through your chest with every exhale. '
    'Your belly rises and falls gently with each breath. '
    '[pause:50s]'
    'Let your lower back soften into the support beneath you. '
    '[pause:70s]'
    'Feel the warmth and stillness spreading down through your hips, your thighs, your knees. '
    'All the way down through your calves, your ankles, the soles of your feet. '
    '[pause:70s]'
    'Your whole body is at rest. '
    'Completely supported. '
    'Completely at ease. '
    '[pause:70s]'
    'Now bring your attention gently back to your breath. '
    'Simply observe each inhale filling you with calm. '
    'And each exhale carrying away whatever you no longer need. '
    '[pause:50s]'
    'Breathe in calm. '
    '[pause:50s]'
    'Breathe out tension. '
    '[pause:70s]'
    'Breathe in presence. '
    '[pause:50s]'
    'Breathe out distraction. '
    '[pause:70s]'
    'You are safe here. '
    'You are grounded. '
    'There is nowhere else you need to be. '
    '[pause:70s]'
    'If any thoughts arise, acknowledge them gently and let them drift away, '
    'like clouds passing across a calm sky. '
    'You do not need to hold on to them. '
    '[pause:70s]'
    'Return always to the breath. '
    'The slow, steady rhythm that anchors you here. '
    '[pause:70s]'
    'Breathe in. '
    '[pause:50s]'
    'And out. '
    '[pause:70s]'
    'Breathe in. '
    '[pause:50s]'
    'And out. '
    '[pause:70s]'
    'With each passing moment, you feel more rested, more restored. '
    'Your mind is quiet. '
    'Your body is calm. '
    '[pause:70s]'
    'Take this stillness with you. '
    'It is always available to you, whenever you choose to return to it. '
    '[pause:70s]'
    'Begin to deepen your breath now. '
    'Slowly bring your awareness back to the room around you. '
    '[pause:50s]'
    'Gently wiggle your fingers and your toes. '
    '[pause:50s]'
    'When you are ready, slowly open your eyes. '
    '[pause:50s]'
    'Well done. '
    'Take a moment to appreciate yourself for showing up. '
    'Carry this sense of peace with you into the rest of your day.';
